### ISSUE TITLE
用户名和密码是什么啊

### ISSUE THREAD

**Issue by keyfall** [tuanzi-ne/Tuanzi#3]
用户名和密码是什么啊

**Comment by tuanzi-ne** [comment]
都是admin

**Comment by keyfall** [comment]
收到



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "团子"<notifications@github.com&gt;; 
发送时间: 2020年9月8日(星期二) 下午5:11
收件人: "tuanzi-ne/Tuanzi"<Tuanzi@noreply.github.com&gt;; 
抄送: "炛"<2536726426@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [tuanzi-ne/Tuanzi] 用户名和密码是什么啊 (#3)





 
都是admin
